---
- name: Check if Swarm is already initialized
  shell: docker info | grep -q "Swarm. active"
  register: swarm_status
  ignore_errors: yes
  changed_when: false

- name: Initialize Swarm on Manager
  command: docker swarm init --advertise-addr {{ swarm_manager_ip | default(ansible_host) }}
  when: swarm_status.rc != 0
  register: swarm_init

- name: Get Swarm join token for workers
  command: docker swarm join-token -q worker
  register: worker_token
  changed_when: false

- name: Save worker token to fact
  set_fact:
    swarm_worker_token: "{{ worker_token.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"