---
- name: Initialize Swarm on Manager
  command: docker swarm init --advertise-addr {{ hostvars[groups['managers'][0]]['ansible_host'] }}
  register: swarm_init
  changed_when: "'Swarm initialized' in swarm_init.stdout or 'This node is already part of a swarm' in swarm_init.stderr"
  failed_when: "swarm_init.rc != 0 and 'This node is already part of a swarm' not in swarm_init.stderr"

- name: Get Swarm join token for workers
  command: docker swarm join-token -q worker
  register: worker_token

- name: Save worker token to fact
  set_fact:
    swarm_worker_token: "{{ worker_token.stdout }}"

- name: Share token with other hosts
  debug:
    msg: "Worker join token: {{ swarm_worker_token }}"
